apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: schoolofcloud/demo:0.0.3
          imagePullPolicy: Always
      ports:
        - containerPort: 8080  
      livenessProbe:           
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 15
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        timeoutSeconds: 1  
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort # If you're deploying to a public cloud (e.g. AWS/GCP/Azure) use LoadBalancer, NodePort can be used to test locally
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: demo